const actionTypes = {
	//page
	SYST_LANG_SET: "SYST_LANG_SET",
	DEVICE_DATA_LOADED: "DEVICE_DATA_LOADED",
	PAGE_CHANGED: "PAGE_CHANGED",
	SHOW_FULL_PAGE_LOADER: "SHOW_FULL_PAGE_LOADER",
	HIDE_FULL_PAGE_LOADER: "HIDE_FULL_PAGE_LOADER",

	STORE_CREATED: "STORE_CREATED",
	UPDATE_STORE_DETAILS: "UPDATE_STORE_DETAILS"
};

export default actionTypes;
